# CartIt Ansible Inventory
# Update IPs after terraform apply

[bastion]
bastion ansible_host=BASTION_PUBLIC_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/cartit-bastion.pem

[jenkins]
jenkins ansible_host=JENKINS_PRIVATE_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/cartit-jenkins.pem
jenkins ansible_ssh_common_args='-o ProxyJump=ec2-user@BASTION_PUBLIC_IP'

[sonarqube]
sonarqube ansible_host=SONARQUBE_PRIVATE_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/cartit-sonarqube.pem
sonarqube ansible_ssh_common_args='-o ProxyJump=ec2-user@BASTION_PUBLIC_IP'
