apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
namespace: cartit
images:
  - name: ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/cartit-frontend
    newTag: "latest"
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: cartit-frontend
